parameters:
#    aripd_mobile.example.class: ARIPD\MobileBundle\Example

services:
#    aripd_mobile.example:
#        class: %aripd_mobile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  