<?php
namespace ARIPD\AdminBundle\DataFixtures\ORM;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\AbstractFixture;
use ARIPD\AdminBundle\Entity\Iso3166;

class Iso3166Fixtures extends AbstractFixture {
	
	public function load(ObjectManager $manager) {
		$arrs = array(
				array('Afghanistan', 'Afġānistān / افغانستان', '004', 'AF', 'AFG', '93', '1'),
				array('Albania', 'Shqipëria', '008', 'AL', 'ALB', '355', '1'),
				array('Antarctica', '', '010', 'AQ', 'ATA', '672', '0'),
				array('Algeria', 'الجزائر', '012', 'DZ', 'DZA', '213', '1'),
				array('American Samoa', 'American Samoa', '016', 'AS', 'ASM', '+1-684', '1'),
				array('Andorra', 'Andorra', '020', 'AD', 'AND', '376', '1'),
				array('Angola', 'Angola', '024', 'AO', 'AGO', '244', '1'),
				array('Antigua and Barbuda', 'Antigua and Barbuda', '028', 'AG', 'ATG', '+1-268', '1'),
				array('Azerbaijan', 'Azərbaycan', '031', 'AZ', 'AZE', '994', '1'),
				array('Argentina', 'Argentina', '032', 'AR', 'ARG', '54', '1'),
				array('Australia', 'Australia', '036', 'AU', 'AUS', '61', '1'),
				array('Austria', 'Österreich', '040', 'AT', 'AUT', '43', '1'),
				array('Bahamas', 'The Bahamas', '044', 'BS', 'BHS', '+1-242', '1'),
				array('Bahrain', 'البحرين', '048', 'BH', 'BHR', '973', '1'),
				array('Bangladesh', 'Banglādeś', '050', 'BD', 'BGD', '880', '1'),
				array('Armenia', 'Hayastan / Հայաստան', '051', 'AM', 'ARM', '374', '1'),
				array('Barbados', 'Barbados', '052', 'BB', 'BRB', '+1-246', '1'),
				array('Belgium', 'België', '056', 'BE', 'BEL', '32', '1'),
				array('Bermuda', 'Bermuda', '060', 'BM', 'BMU', '+1-441', '1'),
				array('Bhutan', 'Druk Yul', '064', 'BT', 'BTN', '975', '1'),
				array('Bolivia', 'Bolivia', '068', 'BO', 'BOL', '591', '1'),
				array('Bosnia and Herzegovina', 'Bosna i Hercegovina / Босна и Херцеговина', '070', 'BA', 'BIH', '387', '1'),
				array('Botswana', 'Botswana', '072', 'BW', 'BWA', '267', '1'),
				array('Bouvet Island', '', '074', 'BV', 'BVT', '', '0'),
				array('Brazil', 'Brasil', '076', 'BR', 'BRA', '55', '1'),
				array('Belize', 'Belize', '084', 'BZ', 'BLZ', '501', '1'),
				array('British Indian Ocean Territory', '', '086', 'IO', 'IOT', '', '0'),
				array('Solomon Islands', 'Solomon Islands', '090', 'SB', 'SLB', '677', '1'),
				array('Virgin Islands, British', 'Virgin Islands', '092', 'VG', 'VGB', '+1-284', '1'),
				array('Brunei Darussalam', 'Brunei', '096', 'BN', 'BRN', '673', '1'),
				array('Bulgaria', 'България', '100', 'BG', 'BGR', '359', '1'),
				array('Myanmar', 'Myanma', '104', 'MM', 'MMR', '95', '1'),
				array('Burundi', 'Burundi', '108', 'BI', 'BDI', '257', '1'),
				array('Belarus', 'Беларусь', '112', 'BY', 'BLR', '375', '1'),
				array('Cambodia', 'Kâmpŭchea', '116', 'KH', 'KHM', '855', '1'),
				array('Cameroon', 'Cameroon', '120', 'CM', 'CMR', '237', '1'),
				array('Canada', 'Canada', '124', 'CA', 'CAN', '1', '1'),
				array('Cape Verde', 'Cabo Verde', '132', 'CV', 'CPV', '238', '1'),
				array('Cayman Islands', 'Cayman Islands', '136', 'KY', 'CYM', '+1-345', '1'),
				array('Central African Republic', 'Ködörösêse tî Bêafrîka', '140', 'CF', 'CAF', '236', '1'),
				array('Sri Lanka', 'Sri Lankā', '144', 'LK', 'LKA', '94', '1'),
				array('Chad', 'تشاد', '148', 'TD', 'TCD', '235', '1'),
				array('Chile', 'Chile', '152', 'CL', 'CHL', '56', '1'),
				array('China', '中国', '156', 'CN', 'CHN', '86', '1'),
				array('Taiwan, Province of China', '台灣', '158', 'TW', 'TWN', '886', '1'),
				array('Christmas Island', 'Christmas Island', '162', 'CX', 'CXR', '53', '1'),
				array('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', '166', 'CC', 'CCK', '61', '1'),
				array('Colombia ', 'Colombia', '170', 'CO', 'COL', '57', '1'),
				array('Comoros', 'Komori', '174', 'KM', 'COM', '269', '1'),
				array('Mayotte', 'Mayotte', '175', 'YT', 'MYT', '269', '1'),
				array('Congo', 'Congo', '178', 'CG', 'COG', '242', '1'),
				array('Congo, Democratic Republic of the', 'Congo, Democratic Republic of the', '180', 'CD', 'COD', '243', '1'),
				array('Cook Islands', 'Cook Islands', '184', 'CK', 'COK', '682', '1'),
				array('Costa Rica', 'Costa Rica', '188', 'CR', 'CRI', '506', '1'),
				array('Croatia', 'Hrvatska', '191', 'HR', 'HRV', '385', '1'),
				array('Cuba', 'Cuba', '192', 'CU', 'CUB', '53', '1'),
				array('Cyprus', 'Kıbrıs / Κυπρος', '196', 'CY', 'CYP', '357', '0'),
				array('Czech Republic', 'Česká republika', '203', 'CZ', 'CZE', '420', '1'),
				array('Benin', 'Bénin', '204', 'BJ', 'BEN', '229', '1'),
				array('Denmark', 'Danmark', '208', 'DK', 'DNK', '45', '1'),
				array('Dominica', 'Dominica', '212', 'DM', 'DMA', '+1-767', '1'),
				array('Dominican Republic', 'República Dominicana', '214', 'DO', 'DOM', '+1-809', '1'),
				array('Ecuador', 'Ecuador', '218', 'EC', 'ECU', '+593', '1'),
				array('El Salvador', 'El Salvador', '222', 'SV', 'SLV', '+503', '1'),
				array('Equatorial Guinea', 'Guinea Ecuatorial', '226', 'GQ', 'GNQ', '240', '1'),
				array('Ethiopia', 'Ityop\'iya', '231', 'ET', 'ETH', '251', '1'),
				array('Eritrea', 'إرتريا', '232', 'ER', 'ERI', '291', '1'),
				array('Estonia', 'Eesti', '233', 'EE', 'EST', '372', '1'),
				array('Faroe Islands', 'Føroyar', '234', 'FO', 'FRO', '298', '1'),
				array('Falkland Islands (Malvinas)', 'Falkland Islands', '238', 'FK', 'FLK', '500', '1'),
				array('South Georgia and the South Sandwich Islands', '', '239', 'GS', 'SGS', '', '0'),
				array('Fiji', 'Viti', '242', 'FJ', 'FJI', '679', '1'),
				array('Finland', 'Suomi', '246', 'FI', 'FIN', '358', '1'),
				array('Ã…land Islands', '', '248', 'AX', 'ALA', '', '0'),
				array('France', 'République Française', '250', 'FR', 'FRA', '33', '1'),
				array('French Guiana', '', '254', 'GF', 'GUF', '594', '0'),
				array('French Polynesia', 'Polynésie Française', '258', 'PF', 'PYF', '689', '0'),
				array('French Southern Territories', '', '260', 'TF', 'ATF', '', '0'),
				array('Djibouti', 'Djibouti', '262', 'DJ', 'DJI', '253', '1'),
				array('Gabon', 'Gabon', '266', 'GA', 'GAB', '241', '1'),
				array('Georgia', 'Sakartvelo / საქართველო', '268', 'GE', 'GEO', '995', '1'),
				array('Gambia', 'The Gambia', '270', 'GM', 'GMB', '220', '1'),
				array('Palestinian Territory, Occupied', 'فلسطين', '275', 'PS', 'PSE', '970', '1'),
				array('Germany', 'Deutschland', '276', 'DE', 'DEU', '49', '1'),
				array('Ghana', 'Ghana', '288', 'GH', 'GHA', '233', '1'),
				array('Gibraltar', '', '292', 'GI', 'GIB', '', '0'),
				array('Kiribati', 'Kiribati', '296', 'KI', 'KIR', '686', '1'),
				array('Greece', 'Ελλάδα', '300', 'GR', 'GRC', '30', '1'),
				array('Greenland', 'Kalaallit Nunaat', '304', 'GL', 'GRL', '299', '1'),
				array('Grenada', 'Grenada', '308', 'GD', 'GRD', '+1-473', '1'),
				array('Guadeloupe', '', '312', 'GP', 'GLP', '590', '0'),
				array('Guam', 'Guåhan', '316', 'GU', 'GUM', '+1-671', '1'),
				array('Guatemala', 'Guatemala', '320', 'GT', 'GTM', '502', '1'),
				array('Guinea', 'Papua Niugini', '324', 'GN', 'GIN', '224', '1'),
				array('Guyana', 'Guyana', '328', 'GY', 'GUY', '592', '1'),
				array('Haiti', 'Ayiti', '332', 'HT', 'HTI', '509', '1'),
				array('Heard Island and McDonald Islands', '', '334', 'HM', 'HMD', '', '0'),
				array('Holy See (Vatican City State)', 'Civitas Vaticana', '336', 'VA', 'VAT', '418', '1'),
				array('Honduras', 'Honduras', '340', 'HN', 'HND', '504', '1'),
				array('Hong Kong', 'Hong Kong', '344', 'HK', 'HKG', '852', '1'),
				array('Hungary', 'Magyarország', '348', 'HU', 'HUN', '36', '1'),
				array('Iceland', 'Ísland', '352', 'IS', 'ISL', '354', '1'),
				array('India', 'भारत', '356', 'IN', 'IND', '91', '1'),
				array('Indonesia', 'Indonesia', '360', 'ID', 'IDN', '62', '1'),
				array('Iran, Islamic Republic of', 'ایران', '364', 'IR', 'IRN', '98', '1'),
				array('Iraq', 'العراق', '368', 'IQ', 'IRQ', '964', '1'),
				array('Ireland', 'Éire', '372', 'IE', 'IRL', '353', '1'),
				array('Israel', 'ישראל', '376', 'IL', 'ISR', '972', '1'),
				array('Italy', 'Italia', '380', 'IT', 'ITA', '39', '1'),
				array('Côte d\'Ivoire (Ivory Coast)', '', '384', 'CI', 'CIV', '225', '0'),
				array('Jamaica', 'Jamaica', '388', 'JM', 'JAM', '+1-876', '1'),
				array('Japan', 'Nihon / 日本', '392', 'JP', 'JPN', '81', '1'),
				array('Kazakhstan', 'Qazaqstan / Қазақстан', '398', 'KZ', 'KAZ', '7', '1'),
				array('Jordan', 'الاردن', '400', 'JO', 'JOR', '962', '1'),
				array('Kenya', 'Kenya', '404', 'KE', 'KEN', '254', '1'),
				array('Korea, Democratic People\'s Republic of', '조선', '408', 'KP', 'PRK', '850', '1'),
				array('Korea, Republic of', '한국(韓國) / 대한민국(大韓民國)', '410', 'KR', 'KOR', '82', '1'),
				array('Kuwait', 'الكويت', '414', 'KW', 'KWT', '965', '1'),
				array('Kyrgyzstan', 'Kyrgyzstan / Кыргызстан', '417', 'KG', 'KGZ', '996', '1'),
				array('Lao People\'s Democratic Republic', 'Lao', '418', 'LA', 'LAO', '856', '1'),
				array('Lebanon', 'لبنان', '422', 'LB', 'LBN', '961', '1'),
				array('Lesotho', 'Lesotho', '426', 'LS', 'LSO', '266', '1'),
				array('Latvia', 'Latvija', '428', 'LV', 'LVA', '371', '1'),
				array('Liberia', 'Liberia', '430', 'LR', 'LBR', '231', '1'),
				array('Libyan Arab Jamahiriya', 'Libya', '434', 'LY', 'LBY', '218', '1'),
				array('Liechtenstein', 'Liechtenstein', '438', 'LI', 'LIE', '423', '1'),
				array('Lithuania', 'Lietuva', '440', 'LT', 'LTU', '370', '1'),
				array('Luxembourg', 'Lëtzebuerg', '442', 'LU', 'LUX', '352', '1'),
				array('Macao', '', '446', 'MO', 'MAC', '853', '0'),
				array('Madagascar', 'Madagasikara', '450', 'MG', 'MDG', '261', '1'),
				array('Malawi', 'Malaŵi', '454', 'MW', 'MWI', '265', '1'),
				array('Malaysia', 'Malaysia', '458', 'MY', 'MYS', '60', '1'),
				array('Maldives', 'ގުޖޭއްރާ ޔާއްރިހޫމްޖު', '462', 'MV', 'MDV', '960', '1'),
				array('Mali', 'Mali', '466', 'ML', 'MLI', '223', '1'),
				array('Malta', 'Malta', '470', 'MT', 'MLT', '356', '1'),
				array('Martinique', '', '474', 'MQ', 'MTQ', '596', '0'),
				array('Mauritania', 'موريتانيا', '478', 'MR', 'MRT', '222', '1'),
				array('Mauritius', 'Maurice', '480', 'MU', 'MUS', '230', '1'),
				array('Mexico', 'México', '484', 'MX', 'MEX', '52', '1'),
				array('Monaco', 'Monaco', '492', 'MC', 'MCO', '377', '1'),
				array('Mongolia', 'Монгол Улс', '496', 'MN', 'MNG', '976', '1'),
				array('Moldova, Republic of', 'Republica Moldova', '498', 'MD', 'MDA', '373', '1'),
				array('Montenegro', 'Црна Гора', '499', 'ME', 'MNE', '382', '1'),
				array('Montserrat', 'Montserrat', '500', 'MS', 'MSR', '+1-664', '1'),
				array('Morocco', 'المغرب', '504', 'MA', 'MAR', '212', '1'),
				array('Mozambique', 'Moçambique', '508', 'MZ', 'MOZ', '258', '1'),
				array('Oman', 'عمان', '512', 'OM', 'OMN', '968', '1'),
				array('Namibia', 'Namibia', '516', 'NA', 'NAM', '264', '1'),
				array('Nauru', 'Naoero', '520', 'NR', 'NRU', '674', '1'),
				array('Nepal', 'नेपाल', '524', 'NP', 'NPL', '977', '1'),
				array('Netherlands', 'Nederland', '528', 'NL', 'NLD', '31', '1'),
				array('Netherlands Antilles', 'Nederlandse Antillen', '530', 'AN', 'ANT', '599', '1'),
				array('Aruba', 'Aruba', '533', 'AW', 'ABW', '297', '1'),
				array('New Caledonia', 'Nouvelle-Calédonie', '540', 'NC', 'NCL', '687', '1'),
				array('Vanuatu', 'Vanuatu', '548', 'VU', 'VUT', '678', '1'),
				array('New Zealand', 'Aotearoa', '554', 'NZ', 'NZL', '64', '1'),
				array('Nicaragua', 'Nicaragua', '558', 'NI', 'NIC', '505', '1'),
				array('Niger', 'Niger', '562', 'NE', 'NER', '227', '1'),
				array('Nigeria', 'Nigeria', '566', 'NG', 'NGA', '234', '1'),
				array('Niue', 'Niue', '570', 'NU', 'NIU', '683', '1'),
				array('Norfolk Island', 'Norfolk Island', '574', 'NF', 'NFK', '672', '1'),
				array('Norway', 'Norge or Noreg', '578', 'NO', 'NOR', '47', '1'),
				array('Northern Mariana Islands', 'Northern Mariana Islands', '580', 'MP', 'MNP', '+1-670', '1'),
				array('United States Minor Outlying Islands', '', '581', 'UM', 'UMI', '', '0'),
				array('Micronesia, Federated States of', 'Micronesia', '583', 'FM', 'FSM', '691', '1'),
				array('Marshall Islands', 'Marshall Islands', '584', 'MH', 'MHL', '692', '1'),
				array('Palau', 'Belau', '585', 'PW', 'PLW', '680', '1'),
				array('Pakistan', 'پاکستان', '586', 'PK', 'PAK', '92', '1'),
				array('Panama', 'Panamá', '591', 'PA', 'PAN', '507', '1'),
				array('Papua New Guinea', 'Papua Niugini', '598', 'PG', 'PNG', '675', '1'),
				array('Paraguay', 'Paraguái', '600', 'PY', 'PRY', '595', '1'),
				array('Peru', 'Perú', '604', 'PE', 'PER', '51', '1'),
				array('Philippines', 'Pilipinas', '608', 'PH', 'PHL', '63', '1'),
				array('Pitcairn', 'Pitcairn Islands', '612', 'PN', 'PCN', '', '0'),
				array('Poland', 'Polska', '616', 'PL', 'POL', '48', '1'),
				array('Portugal', 'Portugal', '620', 'PT', 'PRT', '351', '1'),
				array('Guinea-Bissau', 'Guiné-Bissau', '624', 'GW', 'GNB', '245', '1'),
				array('Timor-Leste', 'Timor-Leste', '626', 'TL', 'TLS', '670', '1'),
				array('Puerto Rico', 'Puerto Rico', '630', 'PR', 'PRI', '+1-787', '1'),
				array('Qatar', 'قطر', '634', 'QA', 'QAT', '+974', '1'),
				array('RÃ©union', '', '638', 'RE', 'REU', '', '0'),
				array('Romania', 'România', '642', 'RO', 'ROU', '+40', '1'),
				array('Russian Federation', 'Россия', '643', 'RU', 'RUS', '+7', '1'),
				array('Rwanda', 'Rwanda', '646', 'RW', 'RWA', '+250', '1'),
				array('Saint Helena', 'Saint Helena', '654', 'SH', 'SHN', '+290', '1'),
				array('Saint Kitts and Nevis', 'Saint Kitts and Nevis', '659', 'KN', 'KNA', '', '0'),
				array('Anguilla', 'Anguilla', '660', 'AI', 'AIA', '+1-264', '1'),
				array('Saint Lucia', 'Saint Lucia', '662', 'LC', 'LCA', '', '0'),
				array('Saint Pierre and Miquelon', 'Saint-Pierre-et-Miquelon', '666', 'PM', 'SPM', '508', '1'),
				array('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', '670', 'VC', 'VCT', '+1-784', '1'),
				array('San Marino', 'San Marino', '674', 'SM', 'SMR', '378', '1'),
				array('Sao Tome and Principe', '', '678', 'ST', 'STP', '', '0'),
				array('Saudi Arabia', 'العربية السعودية', '682', 'SA', 'SAU', '966', '1'),
				array('Senegal', 'Sénégal', '686', 'SN', 'SEN', '221', '1'),
				array('Serbia', 'Србија', '688', 'RS', 'SRB', '381', '1'),
				array('Seychelles', 'Sesel', '690', 'SC', 'SYC', '248', '1'),
				array('Sierra Leone', 'Serra Leoa', '694', 'SL', 'SLE', '232', '1'),
				array('Singapore', 'Singapura', '702', 'SG', 'SGP', '65', '1'),
				array('Slovakia', 'Slovensko', '703', 'SK', 'SVK', '421', '1'),
				array('Viet Nam', 'Việt Nam', '704', 'VN', 'VNM', '84', '1'),
				array('Slovenia', 'Slovenija', '705', 'SI', 'SVN', '386', '1'),
				array('Somalia', 'Somaliland', '706', 'SO', 'SOM', '252', '1'),
				array('South Africa', 'Suid-Afrika', '710', 'ZA', 'ZAF', '27', '1'),
				array('Zimbabwe', 'Zimbabwe', '716', 'ZW', 'ZWE', '263', '1'),
				array('Spain', 'España', '724', 'ES', 'ESP', '34', '1'),
				array('Western Sahara', '', '732', 'EH', 'ESH', '', '0'),
				array('Sudan', 'السودان', '736', 'SD', 'SDN', '249', '1'),
				array('Suriname', 'Suriname', '740', 'SR', 'SUR', '597', '1'),
				array('Svalbard and Jan Mayen', 'Svalbard', '744', 'SJ', 'SJM', '', '0'),
				array('Swaziland', 'eSwatini', '748', 'SZ', 'SWZ', '268', '1'),
				array('Sweden', 'Sverige', '752', 'SE', 'SWE', '46', '1'),
				array('Switzerland', 'Schweiz', '756', 'CH', 'CHE', '41', '1'),
				array('Syrian Arab Republic', 'سورية', '760', 'SY', 'SYR', '963', '1'),
				array('Tajikistan', 'Tojikistan / Тоҷикистон', '762', 'TJ', 'TJK', '992', '1'),
				array('Thailand', 'ประเทศไทย', '764', 'TH', 'THA', '66', '1'),
				array('Togo', 'Togo', '768', 'TG', 'TGO', '228', '1'),
				array('Tokelau', 'Tokelau', '772', 'TK', 'TKL', '690', '1'),
				array('Tonga', 'Tonga', '776', 'TO', 'TON', '676', '1'),
				array('Trinidad and Tobago', 'Trinidad and Tobago', '780', 'TT', 'TTO', '+1-868', '1'),
				array('United Arab Emirates', 'الإمارات العربيّة المتّحدة', '784', 'AE', 'ARE', '971', '1'),
				array('Tunisia', 'تونس', '788', 'TN', 'TUN', '216', '1'),
				array('Turkey', 'Türkiye', '792', 'TR', 'TUR', '90', '1'),
				array('Turkmenistan', 'Türkmenistan', '795', 'TM', 'TKM', '993', '1'),
				array('Turks and Caicos Islands', 'Turks and Caicos Islands', '796', 'TC', 'TCA', '+1-649', '1'),
				array('Tuvalu', 'Tuvalu', '798', 'TV', 'TUV', '688', '1'),
				array('Uganda', 'Uganda', '800', 'UG', 'UGA', '256', '1'),
				array('Ukraine', 'Україна', '804', 'UA', 'UKR', '380', '1'),
				array('Macedonia, the former Yugoslav Republic of', 'Makedonija / Македонија', '807', 'MK', 'MKD', '389', '1'),
				array('Egypt', 'مصر', '818', 'EG', 'EGY', '+20', '1'),
				array('United Kingdom', 'United Kingdom', '826', 'GB', 'GBR', '44', '1'),
				array('Guernsey', 'Guernsey', '831', 'GG', 'GGY', '', '0'),
				array('Jersey', 'Jersey', '832', 'JE', 'JEY', '', '0'),
				array('Isle of Man', 'Ellan Vannin', '833', 'IM', 'IMN', '', '0'),
				array('Tanzania, United Republic of', 'Tanzania', '834', 'TZ', 'TZA', '255', '1'),
				array('United States', 'United States of America', '840', 'US', 'USA', '1', '1'),
				array('Virgin Islands, U.S.', '', '850', 'VI', 'VIR', '+1-340', '0'),
				array('Burkina Faso', 'Burkina Faso', '854', 'BF', 'BFA', '226', '1'),
				array('Uruguay', 'Uruguay', '858', 'UY', 'URY', '598', '1'),
				array('Uzbekistan', 'Ŭzbekiston or Özbekistân / Ўзбекистон', '860', 'UZ', 'UZB', '998', '1'),
				array('Venezuela', 'Venezuela', '862', 'VE', 'VEN', '58', '1'),
				array('Wallis and Futuna', 'Wallis-et-Futuna', '876', 'WF', 'WLF', '681', '1'),
				array('Samoa', 'Samoa', '882', 'WS', 'WSM', '685', '1'),
				array('Yemen', 'اليمن', '887', 'YE', 'YEM', '967', '1'),
				array('Zambia', 'Zambia', '894', 'ZM', 'ZMB', '260', '1'),);

		foreach ($arrs as $arr) {
			$entity = new Iso3166();
			$entity->setName($arr[0]);
			$entity->setNative($arr[1]);
			$entity->setAn($arr[2]);
			$entity->setA2($arr[3]);
			$entity->setA3($arr[4]);
			$entity->setPhonecode($arr[5]);
			$entity->setActive($arr[6]);
			
			$manager->persist($entity);
			$this->addReference('aripdadmin_iso3166-' . $entity->getA2(), $entity);
		}

		$manager->flush();
	}
	
}
