imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@ARIPDAdminBundle/Resources/config/services.yml" }
    - { resource: "@ARIPDAdsBundle/Resources/config/services.yml" }
    - { resource: "@ARIPDCMSBundle/Resources/config/services.yml" }
    - { resource: "@ARIPDStoreBundle/Resources/config/services.yml" }
    - { resource: "@ARIPDUserBundle/Resources/config/services.yml" }
    - { resource: "@BCCCronManagerBundle/Resources/config/assetic.yml" }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    #router_proxy:   { path: /_proxy }

# Twig Configuration, http://symfony.com/doc/master/reference/configuration/twig.html
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache:            false
    globals:
        locales:  "%locales%"
        theme_active: "%theme_active%"

# Assetic Configuration, http://symfony.com/doc/master/reference/configuration/assetic.html
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ BCCCronManagerBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database.driver%"
        host:     "%database.host%"
        port:     "%database.port%"
        dbname:   "%database.dbname%"
        user:     "%database.user%"
        password: "%database.password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    #encryption: "%mailer_encryption%"
    #auth_mode:  "%mailer_auth_mode%"
    #port:       "%mailer_port%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }
    logging:    "%kernel.debug%"




liip_theme:
    themes: "%themes%"
    active_theme: "%theme_active%"

jms_security_extra:
    expressions: true

jms_i18n_routing:
    default_locale: "%locale%"
    locales:        "%locales%"
    strategy:       prefix_except_default

jms_translation:
    configs:
        app:
            dirs: [ "%kernel.root_dir%", "%kernel.root_dir%/../src" ]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: [ routes ]
            excluded_names: [ "*TestCase.php", "*Test.php" ]
            excluded_dirs: [ cache, data, logs ]
            extractors: [ jms_i18n_routing ]

services:
    twig.text_extension: # http://www.symfony-grenoble.fr/144/utiliser-les-extensions-twig-natives-de-symfony-2/
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    #twig.extension.intl:
    #    class: Twig_Extensions_Extension_Intl
    #    tags:
    #        - { name: twig.extension }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ARIPD\UserBundle\Entity\User
    from_email:
        address:     "%mail_sender_address%"
        sender_name: "%mail_sender_name%"
    service:
        mailer: fos_user.mailer.twig_swift
    group:
        group_class: ARIPD\UserBundle\Entity\Group
        form:
            type: aripdadmin_usergroupformtype
    profile:
        form:
            type: aripduser_profileformtype
    registration:
        form:
            type: aripduser_registrationformtype
        confirmation:
            enabled:  true
            template: ARIPDUserBundle:Registration:email.txt.twig
    resetting:
        email:
            template: ARIPDUserBundle:Resetting:email.txt.twig
            
fos_facebook:
    alias:       facebook
    app_id:      "%facebook.app_id%"
    secret:      "%facebook.secret%"
    cookie:      true
    permissions: [email, user_birthday, user_location]