_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml




_gchart:
    resource: "@SaadTaziGChartBundle/Resources/config/routing.yml"
    type:     yaml
    prefix:   /gchart

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans

BCCCronManagerBundle:
    resource: "@BCCCronManagerBundle/Resources/config/routing.xml"
    prefix:   /cron-manager

