aripd_intranet:
    resource: "@ARIPDIntranetBundle/Controller/"
    type:     annotation
    prefix:   /intranet

aripdscm:
    resource: "@ARIPDSCMBundle/Controller/"
    type:     annotation
    prefix:   /scm

aripd_admin:
    resource: "@ARIPDAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

aripd_user:
    resource: "@ARIPDUserBundle/Controller/"
    type:     annotation
    prefix:   /user

aripd_mobile:
    resource: "@ARIPDMobileBundle/Controller/"
    type:     annotation
    prefix:   /mobile
    
aripd_config:
    resource: "@ARIPDConfigBundle/Controller/"
    type:     annotation
    prefix:   /config

aripd_default:
    resource: "@ARIPDDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

aripd_store:
    resource: "@ARIPDStoreBundle/Controller/"
    type:     annotation
    prefix:   /store

aripd_dms:
    resource: "@ARIPDDMSBundle/Controller/"
    type:     annotation
    prefix:   /dms

aripd_forum:
    resource: "@ARIPDForumBundle/Controller/"
    type:     annotation
    prefix:   /forum

aripd_blog:
    resource: "@ARIPDBlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

aripd_ads:
    resource: "@ARIPDAdsBundle/Controller/"
    type:     annotation
    prefix:   /ads

aripd_cms:
    resource: "@ARIPDCMSBundle/Controller/"
    type:     annotation
    prefix:   /cms

aripd_crm:
    resource: "@ARIPDCRMBundle/Controller/"
    type:     annotation
    prefix:   /crm

aripd_stock:
    resource: "@ARIPDStockBundle/Controller/"
    type:     annotation
    prefix:   /stock

aripd_survey:
    resource: "@ARIPDSurveyBundle/Controller/"
    type:     annotation
    prefix:   /survey

aripd_shopping:
    resource: "@ARIPDShoppingBundle/Controller/"
    type:     annotation
    prefix:   /shopping

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /profile



fos_facebook_security_check:
    pattern:  /login_check_fb



fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
