jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPERADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    #acl:
    #    connection: default

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        fos_facebook_provider:
            id: aripduser.facebook_provider
        chain_provider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            context: primary_auth
            pattern: ^/
            anonymous: true
            fos_facebook:
                login_path: /login
                check_path: fos_facebook_security_check
                provider: fos_facebook_provider
            form_login:
                provider: chain_provider
                login_path: /login
                check_path: fos_user_security_check
                #always_use_default_target_path: true
                default_target_path: aripd_default_index
                #-----------------
                #use_referer: true
                csrf_provider: form.csrf_provider
                #failure_path:  null
                #failure_forward: false
                #success_handler: aripduser.authentication_listener
                #failure_handler: aripduser.authentication_listener
            logout:
                path:   fos_user_security_logout
                target: aripd_default_index
                success_handler: aripduser.authentication_listener
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            switch_user:
                role: ROLE_SUPERADMIN

    access_control:
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }